projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: cbhs36ysffgclfv7qpmhgycunq
        frontend: javascript
        framework: none
        maxDepth: 5
extensions:
  amplify:
    version: 3
